lst = [20, 1, -34, 40, -8, 60, 1, 3]

print("(a)", lst)
print("(b)", lst[0:3])
print("(c)", lst[4:8])
print("(d)", lst[4:33])
print("(e)", lst[-5:-3])
print("(f)", lst[-22:3])
print("(g)", lst[4:])
print("(h)", lst[:])
print("(i)", lst[:4])
print("(j)", lst[1:5])
print("(k)", -34 in lst)
print("(l)", -34 not in lst)
print("(m)", len(lst))